name: Deploy Nuxt Dashboard to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dashboard

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # - name: Fetch data from API
      #   run: |
      #     curl -s https://api.example.com/data > public/data.json
      #     cat public/data.json

      - name: Build Nuxt app
        run: npm run build

      - name: Export static site
        run: npm run generate

      - name: Debug directory structure
        working-directory: ${{ github.workspace }}
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing repository root:"
          ls -la
          echo "Listing dashboard directory:"
          ls -la dashboard/
          echo "Looking for dist directory:"
          find . -name "dist" -type d

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/dashboard/dist
